"""
Sandboxed SQL execution.

Every query in this project - generated by a model, written by hand, or typed
into the demo - goes through `run()`. Nothing else opens the warehouse.

Four independent defences, in order of how much they are trusted:

1. **Read-only connection.** The engine itself refuses writes. This is the
   defence that actually matters; the rest are depth.
2. **Statement validation.** One statement, starting with a read verb, with no
   forbidden keyword anywhere. Blocks things a read-only connection does not:
   COPY ... TO writes files, ATTACH mounts a writable database, INSTALL/LOAD
   pull in extensions, SET changes configuration.
3. **Timeout.** The query runs on a worker thread; the caller interrupts it if
   it overruns. A model that writes a cartesian join across two million-row
   tables should cost ten seconds, not the afternoon.
4. **Row cap.** Results are fetched lazily and capped, so a query returning
   fifteen million rows returns the cap and a truncation flag.

Errors are classified rather than returned as strings, because stage 7's
error taxonomy needs to count failure kinds and free text cannot be counted.

Self-test:
    python src/sandbox.py
"""

from __future__ import annotations

import re
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import duckdb

DB_PATH = Path("data/olist.duckdb")
MAX_ROWS = 1_000
TIMEOUT_S = 10.0

# Statements may begin with these. DuckDB permits FROM-first syntax, so it is
# included. Defence in depth only - anything added here must be read-only.
ALLOWED_STARTS = {
    "select", "with", "from", "explain", "describe", "show", "values", "table",
    "summarize", "pivot", "unpivot",
}

# Blocked anywhere in the statement. Read-only already stops most of these;
# COPY, ATTACH, INSTALL and LOAD are the ones it does not.
FORBIDDEN = {
    "insert", "update", "delete", "drop", "create", "alter", "truncate",
    "attach", "detach", "copy", "install", "load", "pragma", "set", "reset",
    "export", "import", "call", "vacuum", "checkpoint", "grant", "revoke",
    "begin", "commit", "rollback", "use",
}

ERROR_KINDS = ("blocked", "syntax", "unknown_object", "type_error",
               "timeout", "runtime")


@dataclass
class QueryResult:
    """Outcome of one sandboxed execution."""
    ok: bool
    sql: str
    columns: list[str] = field(default_factory=list)
    rows: list[tuple] = field(default_factory=list)
    truncated: bool = False
    elapsed_ms: float = 0.0
    error: str | None = None
    error_kind: str | None = None

    @property
    def row_count(self) -> int:
        return len(self.rows)

    def __repr__(self) -> str:
        if self.ok:
            t = " (truncated)" if self.truncated else ""
            return (f"<QueryResult ok rows={self.row_count}{t} "
                    f"cols={len(self.columns)} {self.elapsed_ms:.0f}ms>")
        return f"<QueryResult {self.error_kind}: {self.error}>"


def _strip_literals(sql: str) -> str:
    """Blank out string literals, quoted identifiers and comments.

    Validation runs on the result, so a semicolon inside a string and the word
    DROP inside a comment are both harmless - and a column genuinely named
    "drop" does not trip the keyword filter.
    """
    out: list[str] = []
    i, n = 0, len(sql)
    while i < n:
        c = sql[i]
        if c in "'\"":
            quote = c
            i += 1
            while i < n:
                if sql[i] == quote:
                    if i + 1 < n and sql[i + 1] == quote:   # doubled = escaped
                        i += 2
                        continue
                    i += 1
                    break
                i += 1
            out.append(" ")
        elif c == "$" and sql.startswith("$$", i):
            i += 2
            end = sql.find("$$", i)
            i = n if end == -1 else end + 2
            out.append(" ")
        elif c == "-" and sql.startswith("--", i):
            while i < n and sql[i] != "\n":
                i += 1
            out.append(" ")
        elif c == "/" and sql.startswith("/*", i):
            end = sql.find("*/", i + 2)
            i = n if end == -1 else end + 2
            out.append(" ")
        else:
            out.append(c)
            i += 1
    return "".join(out)


def validate(sql: str) -> tuple[str, str] | None:
    """Return (reason, error_kind) if the statement may not run, else None.

    Order matters. A forbidden keyword is checked *before* the opening verb,
    so `DROP TABLE orders` is reported as blocked while `SELEC 1` is reported
    as a syntax error. Both are refused; only the label differs - and stage 7
    counts those labels, so conflating a typo with an attempted write would
    overstate how often the guardrails fired.
    """
    if not sql or not sql.strip():
        return "empty statement", "blocked"

    stripped = _strip_literals(sql).strip()
    stripped = stripped.rstrip().removesuffix(";").strip()

    if ";" in stripped:
        return "multiple statements are not permitted", "blocked"

    words = re.findall(r"[a-zA-Z_]+", stripped.lower())
    if not words:
        return "no statement found", "blocked"

    hit = FORBIDDEN.intersection(words)
    if hit:
        return f"forbidden keyword: {', '.join(sorted(hit))}", "blocked"

    if words[0] not in ALLOWED_STARTS:
        return f"unrecognised statement verb '{words[0]}'", "syntax"

    return None


def _classify(exc: BaseException) -> tuple[str, str]:
    """Map a DuckDB exception onto a countable error kind."""
    name = type(exc).__name__
    msg = str(exc).strip().splitlines()[0] if str(exc).strip() else name
    if "Interrupt" in name:
        return "timeout", msg
    if "Parser" in name or "Syntax" in name:
        return "syntax", msg
    if "Binder" in name or "Catalog" in name:
        return "unknown_object", msg
    if "Conversion" in name or "Type" in name or "Cast" in name:
        return "type_error", msg
    return "runtime", msg


def connect(db_path: Path | str = DB_PATH) -> duckdb.DuckDBPyConnection:
    """Open the warehouse read-only, with external file access off if possible."""
    db_path = Path(db_path)
    if not db_path.exists():
        raise FileNotFoundError(f"{db_path} - run src/01_build_warehouse.py first")
    try:
        return duckdb.connect(str(db_path), read_only=True,
                              config={"enable_external_access": "false"})
    except Exception:
        # Older DuckDB builds reject the setting; read_only still applies.
        return duckdb.connect(str(db_path), read_only=True)


def run(sql: str,
        con: duckdb.DuckDBPyConnection | None = None,
        max_rows: int = MAX_ROWS,
        timeout_s: float = TIMEOUT_S) -> QueryResult:
    """Execute one statement under the sandbox. Never raises for bad SQL."""
    rejection = validate(sql)
    if rejection:
        reason, kind = rejection
        return QueryResult(ok=False, sql=sql, error=reason, error_kind=kind)

    owned = con is None
    con = con or connect()
    cur = con.cursor()                     # independent execution context
    statement = sql.strip().rstrip(";")
    box: dict[str, Any] = {}

    def work() -> None:
        try:
            cur.execute(statement)
            box["columns"] = [d[0] for d in cur.description] if cur.description else []
            box["rows"] = cur.fetchmany(max_rows + 1)
        except BaseException as exc:       # noqa: BLE001 - classified below
            box["exc"] = exc

    start = time.perf_counter()
    thread = threading.Thread(target=work, daemon=True)
    thread.start()
    thread.join(timeout_s)

    if thread.is_alive():
        try:
            cur.interrupt()
        except Exception:
            pass
        thread.join(2.0)
        elapsed = (time.perf_counter() - start) * 1000
        if owned:
            con.close()
        return QueryResult(ok=False, sql=sql, elapsed_ms=elapsed,
                           error=f"exceeded {timeout_s:g}s", error_kind="timeout")

    elapsed = (time.perf_counter() - start) * 1000

    if "exc" in box:
        kind, msg = _classify(box["exc"])
        if owned:
            con.close()
        return QueryResult(ok=False, sql=sql, elapsed_ms=elapsed,
                           error=msg, error_kind=kind)

    rows = box.get("rows", [])
    truncated = len(rows) > max_rows
    if owned:
        con.close()
    return QueryResult(ok=True, sql=sql, columns=box.get("columns", []),
                       rows=rows[:max_rows], truncated=truncated,
                       elapsed_ms=elapsed)


# --------------------------------------------------------------------------
# Self-test
# --------------------------------------------------------------------------

REVENUE_SQL = """
SELECT sum(oi.price)
FROM order_items oi
JOIN orders o ON o.order_id = oi.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable')
"""

# label, sql, expected outcome: ok | a specific error_kind
CASES: list[tuple[str, str, str]] = [
    ("canonical revenue runs", REVENUE_SQL, "ok"),
    ("CTE allowed", "WITH t AS (SELECT 1 AS x) SELECT x FROM t", "ok"),
    ("FROM-first allowed", "FROM orders SELECT count(*)", "ok"),
    ("trailing semicolon fine", "SELECT 1;", "ok"),
    ("semicolon inside string", "SELECT 'a;b' AS s", "ok"),
    ("DROP inside comment", "SELECT 1 /* DROP TABLE orders */", "ok"),

    ("DROP blocked", "DROP TABLE orders", "blocked"),
    ("DELETE blocked", "DELETE FROM orders", "blocked"),
    ("COPY to file blocked", "COPY orders TO 'leak.csv'", "blocked"),
    ("ATTACH blocked", "ATTACH 'evil.db' AS evil", "blocked"),
    ("INSTALL blocked", "INSTALL httpfs", "blocked"),
    ("PRAGMA blocked", "PRAGMA database_list", "blocked"),
    ("stacked statements blocked", "SELECT 1; DROP TABLE orders", "blocked"),
    ("hidden second statement", "SELECT 1; -- harmless\nDELETE FROM orders",
     "blocked"),
    ("empty rejected", "   ", "blocked"),

    ("syntax error caught", "SELEC 1", "syntax"),
    ("unknown column caught", "SELECT nope FROM orders", "unknown_object"),
    ("unknown table caught", "SELECT * FROM no_such_table", "unknown_object"),

    ("row cap applies", "SELECT * FROM geolocation", "ok"),
    ("timeout fires",
     "SELECT count(*) FROM geolocation a, geolocation b, geolocation c",
     "timeout"),
]


def _self_test() -> int:
    con = connect()
    print("=" * 76)
    print("SANDBOX SELF-TEST")
    print("=" * 76)
    print(f"  db {DB_PATH}   row cap {MAX_ROWS:,}   timeout {TIMEOUT_S:g}s\n")

    failures = 0
    for label, sql, expect in CASES:
        res = run(sql, con=con)
        actual = "ok" if res.ok else res.error_kind
        passed = actual == expect
        failures += not passed
        mark = "PASS" if passed else "FAIL"
        detail = ""
        if res.ok and res.truncated:
            detail = f"capped at {res.row_count:,} rows"
        elif res.ok:
            detail = f"{res.row_count:,} rows, {res.elapsed_ms:.0f}ms"
        else:
            detail = (res.error or "")[:44]
        print(f"  {mark}  {label:<32} {actual:<15} {detail}")

    print()
    rev = run(REVENUE_SQL, con=con)
    value = rev.rows[0][0] if rev.ok and rev.rows else None
    expected = 13_494_400.74
    if value is not None and abs(value - expected) < 0.01:
        print(f"  PASS  revenue matches reference value {value:,.2f}")
    else:
        failures += 1
        print(f"  FAIL  revenue {value} != reference {expected:,.2f}")

    con.close()
    print()
    print("=" * 76)
    print(f"{len(CASES) + 1 - failures} of {len(CASES) + 1} passed")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(_self_test())
